"""Fix missing tables

Revision ID: 0b4f66ea7bbd
Revises: f4aca52beba2
Create Date: 2025-03-24 19:58:30.684097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4f66ea7bbd'
down_revision: Union[str, None] = 'f4aca52beba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
