"""Add freebies table

Revision ID: d7cfb0413c7a
Revises: 0b4f66ea7bbd
Create Date: 2025-03-24 20:03:11.950345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cfb0413c7a'
down_revision: Union[str, None] = '0b4f66ea7bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
